name: screl
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
